# Kubernetes Secrets for API Keys
# Before applying, replace 'your_base64_encoded_api_key' with your actual API key encoded in base64
# To encode: echo -n "your_actual_api_key" | base64

apiVersion: v1
kind: Secret
metadata:
  name: ai-assessment-secrets
type: Opaque
data:
  google-api-key: your_base64_encoded_api_key  # Replace with: echo -n "your_api_key" | base64 